name: gpu-burn
title: GPU Burn
summary: Multi-GPU CUDA stress test
version: 9aefd7c0cc
license: BSD-2-Clause
description: |
  This allows you to run a stress test on your GPUs. Memory usage can
  be controlled by absolute number or percentage. The tool can also be
  run on a single GPU, which is useful if you have a mixed multi-GPU system.

website: http://wili.cc/blog/gpu-burn.html
contact: https://github.com/pedro-avalos/gpu-burn-snap/issues
issues: https://github.com/pedro-avalos/gpu-burn-snap/issues
source-code: https://github.com/wilicc/gpu-burn

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  gpu-burn:
    command: bin/gpu-burn -c $SNAP/usr/share/gpu-burn/compare.ptx
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/cuda/lib:$LD_LIBRARY_PATH
    plugs:
      - opengl
      - hardware-observe
      - network-bind
      - home
      - removable-media

package-repositories:
  - type: apt
    architectures: [amd64]
    formats: [deb]
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64
    priority: 600

parts:
  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-type: git
    source-subdir: glib-only
    plugin: make
    build-packages: [libglib2.0-dev]
    stage-packages: [libglib2.0-bin]

  gpu-burn:
    after: [glib-only]
    plugin: make
    source: https://github.com/wilicc/gpu-burn.git
    source-type: git
    source-commit: 9aefd7c0cc603bbc8c3c102f5338c6af26f8127c
    build-packages: [cuda-toolkit-12-6, libcublas-12-6]
    stage-packages: [libglu1-mesa]
    override-build: |
      make

      mkdir -p $CRAFT_PART_INSTALL/bin \
        $CRAFT_PART_INSTALL/usr/share/gpu-burn \
        $CRAFT_PART_INSTALL/usr/local/cuda/lib

      cp gpu-burn.8 $CRAFT_PART_INSTALL/usr/share/gpu-burn/
      cp LICENSE $CRAFT_PART_INSTALL/usr/share/gpu-burn/
      cp README.md $CRAFT_PART_INSTALL/usr/share/gpu-burn/
      cp compare.ptx $CRAFT_PART_INSTALL/usr/share/gpu-burn/
      cp gpu_burn $CRAFT_PART_INSTALL/usr/share/gpu-burn/
      ln -s ../usr/share/gpu-burn/gpu_burn $CRAFT_PART_INSTALL/bin/gpu-burn

      cp /usr/local/cuda/lib64/libcublas* $CRAFT_PART_INSTALL/usr/local/cuda/lib/
